apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      name: app-pod
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: docker.io/kenphung/app-deploy-statecontroller:latest
        command:
        - sleep
        - "100000"
        env:
        - name: USER_IP
          value: "10.233.69.43"
          #mysql pod ip address
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - nodePort: 30003
    port: 6000
    targetPort: 5000
  selector:
    app: app