apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: 'PQThai29112003'
        - name: MYSQL_DATABASE
          value: 'randomNumberDB'
        - name: MYSQL_USER
          value: 'kenphung'
        - name: MYSQL_HOST
          value: '%'
          # Assign host ip hear
        - name: MYSQL_PASSWORD
          value: 'PQThai29112003'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /data/db
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc