apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  # clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql       
        # command:
        # - /bin/bash
        # - mysql -u root -pPQThai29112003
        # - CREATE DATABASE randomNumberDB;
        # - USE randomNumberDB;
        # - CREATE TABLE randomNumberTable (randomNumber int);
        env:
          # Use secret in real usage
        - name: USER
          value: 999:999
        - name: MYSQL_ROOT_PASSWORD
          value: 'PQThai29112003'
        - name: MYSQL_DATABASE
          value: 'randomNumberDB'
        - name: MYSQL_USER
          value: 'kenphung'
        - name: MYSQL_HOST
          value: '%'
          # Assign host ip hear
        - name: MYSQL_PASSWORD
          value: 'PQThai29112003'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc